# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]  # push or pull_request or ....
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python 3.6
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt update  
        sudo apt install --no-install-recommends python3-minimal python3  
        sudo apt install python3-numpy
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Install apt dependencies
#       run: |
#         sudo apt update  
#         sudo apt install -y python3-numpy
#     - name: Link apt
#       run: |
#         PYTHONPATH="/usr/lib/python${{ matrix.python-version }}/dist-packages:${PYTHONPATH}" nosetests --with-coverage --cover-package=mypkg tests
#         echo $PYTHONPATH
    - name: Test with pytest
      run: |
        #which numpy 
        which python
        python3 -m unittest discover tests
